import type { User, Service, Staff, Appointment, Review, PromoCode, LeaveRequest } from '../types';

// ==================== MOCK USERS ====================
export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Kavindu Perera',
        email: 'customer@demo.com',
        role: 'customer',
        phone: '+94 71 234 5678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavindu',
        loyaltyPoints: 320,
        joinDate: '2024-01-15',
        favoriteStaff: ['s1'],
    },
    {
        id: 'a1',
        name: 'Admin User',
        email: 'admin@demo.com',
        role: 'admin',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
        loyaltyPoints: 0,
        joinDate: '2023-06-01',
    },
    {
        id: 's1',
        name: 'Nimasha Silva',
        email: 'staff@demo.com',
        role: 'staff',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimasha',
        loyaltyPoints: 0,
        joinDate: '2023-09-01',
    },
    {
        id: 's2',
        name: 'Rashmi Fernando',
        email: 'rashmi@demo.com',
        role: 'staff',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rashmi',
        loyaltyPoints: 0,
        joinDate: '2023-10-01',
    },
    {
        id: 's3',
        name: 'Tharushi Jayawardena',
        email: 'tharushi@demo.com',
        role: 'staff',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tharushi',
        loyaltyPoints: 0,
        joinDate: '2023-11-01',
    },
];

// ==================== MOCK SERVICES ====================
export const mockServices: Service[] = [
    {
        id: 'svc1',
        name: 'Classic Hair Cut',
        description: 'A clean, precise haircut tailored to your style.',
        price: 1500,
        duration: 30,
        category: 'Hair',
        isActive: true,
    },
    {
        id: 'svc2',
        name: 'Hair Color & Highlights',
        description: 'Professional coloring with premium products.',
        price: 6500,
        discountPrice: 5500,
        duration: 90,
        category: 'Hair',
        isActive: true,
    },
    {
        id: 'svc3',
        name: 'Hydrating Facial',
        description: 'Deep cleansing and moisture boost for radiant skin.',
        price: 3500,
        duration: 60,
        category: 'Facial',
        isActive: true,
    },
    {
        id: 'svc4',
        name: 'Gold Luxury Facial',
        description: '24k gold infused facial for anti-aging and glow.',
        price: 8000,
        duration: 75,
        category: 'Facial',
        isActive: true,
    },
    {
        id: 'svc5',
        name: 'Bridal Makeup',
        description: 'Full bridal look with HD makeup and accessories.',
        price: 15000,
        duration: 120,
        category: 'Bridal',
        isActive: true,
    },
    {
        id: 'svc6',
        name: 'Bridal Package',
        description: 'Complete bridal prep: hair, makeup, nails & facial.',
        price: 35000,
        discountPrice: 28000,
        duration: 300,
        category: 'Bridal',
        isActive: true,
        isPackage: true,
    },
    {
        id: 'svc7',
        name: 'Gel Nail Extension',
        description: 'Durable gel extensions with your choice of design.',
        price: 4000,
        duration: 60,
        category: 'Nails',
        isActive: true,
    },
    {
        id: 'svc8',
        name: 'Relaxing Head Massage',
        description: 'Stress relief scalp and head massage with oils.',
        price: 2000,
        duration: 45,
        category: 'Massage',
        isActive: true,
    },
    {
        id: 'svc9',
        name: 'Eyebrow Shaping & Threading',
        description: 'Professional shaping for perfect eyebrows.',
        price: 800,
        duration: 20,
        category: 'Makeup',
        isActive: true,
    },
    {
        id: 'svc10',
        name: 'Natural Day Makeup',
        description: 'Soft, natural makeup look for daily wear.',
        price: 3000,
        duration: 45,
        category: 'Makeup',
        isActive: true,
    },
    {
        id: 'svc11',
        name: 'Keratin Hair Treatment',
        description: 'Smooth, frizz-free hair with premium keratin.',
        price: 12000,
        duration: 150,
        category: 'Hair',
        isActive: true,
    },
    {
        id: 'svc12',
        name: 'Anti-Acne Treatment',
        description: 'Specialized facial for acne-prone skin.',
        price: 4500,
        duration: 60,
        category: 'Facial',
        isActive: true,
    }
];

// ==================== MOCK STAFF ====================
export const mockStaff: Staff[] = [
    {
        id: 's1',
        name: 'Nimasha Silva',
        email: 'staff@demo.com',
        phone: '+94 77 111 2222',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimasha',
        specializations: ['Hair', 'Bridal'],
        workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        workingHours: { start: '09:00', end: '18:00' },
        commissionPercentage: 15,
        isOnLeave: false,
        rating: 4.9,
        totalAppointments: 312,
    },
    {
        id: 's2',
        name: 'Rashmi Fernando',
        email: 'rashmi@demo.com',
        phone: '+94 77 333 4444',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rashmi',
        specializations: ['Facial', 'Makeup', 'Nails'],
        workingDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '10:00', end: '19:00' },
        commissionPercentage: 15,
        isOnLeave: false,
        rating: 4.7,
        totalAppointments: 245,
    },
    {
        id: 's3',
        name: 'Tharushi Jayawardena',
        email: 'tharushi@demo.com',
        phone: '+94 77 555 6666',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tharushi',
        specializations: ['Nails', 'Massage'],
        workingDays: ['Monday', 'Wednesday', 'Friday', 'Saturday', 'Sunday'],
        workingHours: { start: '09:00', end: '17:00' },
        commissionPercentage: 12,
        isOnLeave: true,
        leaveUntil: '2026-03-01',
        rating: 4.6,
        totalAppointments: 189,
    },
];

// ==================== MOCK APPOINTMENTS ====================
export const mockAppointments: Appointment[] = [
    {
        id: 'apt1',
        customerId: 'u1',
        customerName: 'Kavindu Perera',
        customerEmail: 'customer@demo.com',
        serviceId: 'svc1',
        serviceName: 'Classic Hair Cut',
        servicePrice: 1500,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-02-24',
        timeSlot: '10:00',
        duration: 30,
        status: 'Confirmed',
        paymentStatus: 'Unpaid',
        paymentMethod: 'Cash',
        createdAt: '2026-02-20T09:00:00Z',
    },
    {
        id: 'apt2',
        customerId: 'u1',
        customerName: 'Kavindu Perera',
        customerEmail: 'customer@demo.com',
        serviceId: 'svc3',
        serviceName: 'Hydrating Facial',
        servicePrice: 3500,
        staffId: 's2',
        staffName: 'Rashmi Fernando',
        date: '2026-02-23',
        timeSlot: '14:00',
        duration: 60,
        status: 'Completed',
        paymentStatus: 'Paid',
        paymentMethod: 'Card',
        createdAt: '2026-02-15T10:30:00Z',
    },
    {
        id: 'apt3',
        customerId: 'u2',
        customerName: 'Sithara De Silva',
        customerEmail: 'sithara@mail.com',
        serviceId: 'svc5',
        serviceName: 'Bridal Makeup',
        servicePrice: 15000,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-02-25',
        timeSlot: '08:00',
        duration: 120,
        status: 'Pending',
        paymentStatus: 'Partial',
        paymentMethod: 'Online',
        createdAt: '2026-02-22T14:00:00Z',
    },
    {
        id: 'apt4',
        customerId: 'u3',
        customerName: 'Malsha Rathnayake',
        customerEmail: 'malsha@mail.com',
        serviceId: 'svc7',
        serviceName: 'Gel Nail Extension',
        servicePrice: 4000,
        staffId: 's2',
        staffName: 'Rashmi Fernando',
        date: '2026-02-23',
        timeSlot: '11:00',
        duration: 60,
        status: 'Confirmed',
        paymentStatus: 'Paid',
        paymentMethod: 'Online',
        createdAt: '2026-02-20T11:00:00Z',
    },
    {
        id: 'apt5',
        customerId: 'u4',
        customerName: 'Dilini Madushika',
        customerEmail: 'dilini@mail.com',
        serviceId: 'svc2',
        serviceName: 'Hair Color & Highlights',
        servicePrice: 5500,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-02-22',
        timeSlot: '13:00',
        duration: 90,
        status: 'Cancelled',
        paymentStatus: 'Refunded',
        createdAt: '2026-02-18T08:00:00Z',
    },
];

// ==================== MOCK REVIEWS ====================
export const mockReviews: Review[] = [
    {
        id: 'r1',
        customerId: 'u1',
        customerName: 'Kavindu Perera',
        staffId: 's1',
        serviceId: 'svc1',
        rating: 5,
        comment: 'Nimasha is absolutely amazing! Perfect cut every time.',
        createdAt: '2026-02-10T10:00:00Z',
    },
    {
        id: 'r2',
        customerId: 'u2',
        customerName: 'Sithara De Silva',
        staffId: 's2',
        serviceId: 'svc3',
        rating: 4,
        comment: 'Great facial, my skin feels so refreshed. Will definitely come back!',
        createdAt: '2026-02-12T15:00:00Z',
    },
];

// ==================== MOCK PROMO CODES ====================
export const mockPromoCodes: PromoCode[] = [
    {
        id: 'p1',
        code: 'WELCOME20',
        discount: 20,
        isActive: true,
        expiresAt: '2026-12-31',
        usageLimit: 100,
        usedCount: 34,
    },
    {
        id: 'p2',
        code: 'BRIDAL15',
        discount: 15,
        isActive: true,
        expiresAt: '2026-06-30',
        usageLimit: 50,
        usedCount: 12,
    },
];

// ==================== REVENUE CHART DATA ====================
export const revenueData = [
    { month: 'Aug', revenue: 145000, appointments: 82 },
    { month: 'Sep', revenue: 162000, appointments: 95 },
    { month: 'Oct', revenue: 138000, appointments: 76 },
    { month: 'Nov', revenue: 195000, appointments: 110 },
    { month: 'Dec', revenue: 235000, appointments: 142 },
    { month: 'Jan', revenue: 178000, appointments: 98 },
    { month: 'Feb', revenue: 210000, appointments: 121 },
];

export const servicePopularity = [
    { name: 'Hair', value: 35 },
    { name: 'Facial', value: 25 },
    { name: 'Bridal', value: 15 },
    { name: 'Nails', value: 15 },
    { name: 'Massage', value: 10 },
];

export const peakHoursData = [
    { hour: '9AM', count: 12 },
    { hour: '10AM', count: 25 },
    { hour: '11AM', count: 30 },
    { hour: '12PM', count: 18 },
    { hour: '1PM', count: 10 },
    { hour: '2PM', count: 22 },
    { hour: '3PM', count: 28 },
    { hour: '4PM', count: 35 },
    { hour: '5PM', count: 20 },
    { hour: '6PM', count: 8 },
];

export const mockLeaveRequests: LeaveRequest[] = [
    {
        id: 'lv1',
        staffId: 's3',
        staffName: 'Tharushi Jayawardena',
        startDate: '2026-02-25',
        endDate: '2026-03-01',
        reason: 'Personal family emergency',
        status: 'Approved',
        appliedAt: '2026-02-20T10:00:00Z',
        approvedAt: '2026-02-21T09:00:00Z'
    },
    {
        id: 'lv2',
        staffId: 's1',
        staffName: 'Nimasha Silva',
        startDate: '2026-03-10',
        endDate: '2026-03-12',
        reason: 'Friend\'s wedding',
        status: 'Pending',
        appliedAt: '2026-02-22T14:30:00Z'
    }
];

export const mockGallery = [
    {
        id: 'g1',
        title: 'Elegant Bridal Makeup',
        category: 'Bridal',
        image: 'https://images.unsplash.com/photo-1594463750939-f6ad2a7144e1?q=80&w=800&auto=format',
    },
    {
        id: 'g2',
        title: 'Modern Pixie Cut',
        category: 'Hair',
        image: 'https://images.unsplash.com/photo-1560869713-7d0a294308ed?q=80&w=800&auto=format',
    },
    {
        id: 'g3',
        title: 'Luxury Gold Facial',
        category: 'Facial',
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format',
    },
    {
        id: 'g4',
        title: 'Nail Art Masterpiece',
        category: 'Nails',
        image: 'https://images.unsplash.com/photo-1604654894610-df490982700d?q=80&w=800&auto=format',
    },
    {
        id: 'g5',
        title: 'Boho Braided Style',
        category: 'Hair',
        image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?q=80&w=800&auto=format',
    },
    {
        id: 'g6',
        title: 'Red Carpet Glamour',
        category: 'Makeup',
        image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800&auto=format',
    },
    {
        id: 'g7',
        title: 'Traditional Wedding Look',
        category: 'Bridal',
        image: 'https://images.unsplash.com/photo-1595152244501-995bc9a0cd47?q=80&w=800&auto=format',
    },
    {
        id: 'g8',
        title: 'Soft Balayage',
        category: 'Hair',
        image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format',
    }
];
