import type { User, Service, Staff, Appointment, Review, PromoCode, LeaveRequest } from '../types';

// ==================== MOCK USERS ====================
export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Kavindu Perera',
        email: 'customer@demo.com',
        role: 'customer',
        phone: '+94 71 234 5678',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavindu',
        loyaltyPoints: 320,
        joinDate: '2024-01-15',
        favoriteStaff: ['s1'],
    },
    {
        id: 'a1',
        name: 'Admin User',
        email: 'admin@demo.com',
        role: 'admin',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
        loyaltyPoints: 0,
        joinDate: '2023-06-01',
    },
    {
        id: 's1',
        name: 'Nimasha Silva',
        email: 'staff@demo.com',
        role: 'staff',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimasha',
        loyaltyPoints: 0,
        joinDate: '2023-09-01',
    },
    {
        id: 's2',
        name: 'Rashmi Fernando',
        email: 'rashmi@demo.com',
        role: 'staff',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rashmi',
        loyaltyPoints: 0,
        joinDate: '2023-10-01',
    },
    {
        id: 's3',
        name: 'Tharushi Jayawardena',
        email: 'tharushi@demo.com',
        role: 'staff',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tharushi',
        loyaltyPoints: 0,
        joinDate: '2023-11-01',
    },
];

// ==================== MOCK SERVICES ====================
export const mockServices: Service[] = [
    {
        id: 'svc1',
        name: 'Classic Hair Cut',
        description: 'A clean, precise haircut tailored to your style.',
        price: 1500,
        duration: 30,
        category: 'Hair',
        isActive: true,
    },
    {
        id: 'svc2',
        name: 'Hair Color & Highlights',
        description: 'Professional coloring with premium products.',
        price: 6500,
        discountPrice: 5500,
        duration: 90,
        category: 'Hair',
        isActive: true,
    },
    {
        id: 'svc3',
        name: 'Hydrating Facial',
        description: 'Deep cleansing and moisture boost for radiant skin.',
        price: 3500,
        duration: 60,
        category: 'Facial',
        isActive: true,
    },
    {
        id: 'svc4',
        name: 'Gold Luxury Facial',
        description: '24k gold infused facial for anti-aging and glow.',
        price: 8000,
        duration: 75,
        category: 'Facial',
        isActive: true,
    },
    {
        id: 'svc5',
        name: 'Bridal Makeup',
        description: 'Full bridal look with HD makeup and accessories.',
        price: 15000,
        duration: 120,
        category: 'Bridal',
        isActive: true,
    },
    {
        id: 'svc6',
        name: 'Bridal Package',
        description: 'Complete bridal prep: hair, makeup, nails & facial.',
        price: 35000,
        discountPrice: 28000,
        duration: 300,
        category: 'Bridal',
        isActive: true,
        isPackage: true,
    },
    {
        id: 'svc7',
        name: 'Gel Nail Extension',
        description: 'Durable gel extensions with your choice of design.',
        price: 4000,
        duration: 60,
        category: 'Nails',
        isActive: true,
    },
    {
        id: 'svc8',
        name: 'Relaxing Head Massage',
        description: 'Stress relief scalp and head massage with oils.',
        price: 2000,
        duration: 45,
        category: 'Massage',
        isActive: true,
    },
    {
        id: 'svc9',
        name: 'Eyebrow Shaping & Threading',
        description: 'Professional shaping for perfect eyebrows.',
        price: 800,
        duration: 20,
        category: 'Makeup',
        isActive: true,
    },
    {
        id: 'svc10',
        name: 'Natural Day Makeup',
        description: 'Soft, natural makeup look for daily wear.',
        price: 3000,
        duration: 45,
        category: 'Makeup',
        isActive: true,
    },
    {
        id: 'svc11',
        name: 'Keratin Hair Treatment',
        description: 'Smooth, frizz-free hair with premium keratin.',
        price: 12000,
        duration: 150,
        category: 'Hair',
        isActive: true,
    },
    {
        id: 'svc12',
        name: 'Anti-Acne Treatment',
        description: 'Specialized facial for acne-prone skin.',
        price: 4500,
        duration: 60,
        category: 'Facial',
        isActive: true,
    }
];

// ==================== MOCK STAFF ====================
export const mockStaff: Staff[] = [
    {
        id: 's1',
        name: 'Nimasha Silva',
        email: 'staff@demo.com',
        phone: '+94 77 111 2222',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nimasha',
        specializations: ['Hair', 'Bridal'],
        workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        workingHours: { start: '09:00', end: '18:00' },
        commissionPercentage: 15,
        isOnLeave: false,
        rating: 4.9,
        totalAppointments: 312,
    },
    {
        id: 's2',
        name: 'Rashmi Fernando',
        email: 'rashmi@demo.com',
        phone: '+94 77 333 4444',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rashmi',
        specializations: ['Facial', 'Makeup', 'Nails'],
        workingDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '10:00', end: '19:00' },
        commissionPercentage: 15,
        isOnLeave: false,
        rating: 4.7,
        totalAppointments: 245,
    },
    {
        id: 's3',
        name: 'Tharushi Jayawardena',
        email: 'tharushi@demo.com',
        phone: '+94 77 555 6666',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tharushi',
        specializations: ['Nails', 'Massage'],
        workingDays: ['Monday', 'Wednesday', 'Friday', 'Saturday', 'Sunday'],
        workingHours: { start: '09:00', end: '17:00' },
        commissionPercentage: 12,
        isOnLeave: true,
        leaveUntil: '2026-03-01',
        rating: 4.6,
        totalAppointments: 189,
    },
];

// ==================== MOCK APPOINTMENTS ====================
export const mockAppointments: Appointment[] = [
    {
        id: 'apt1',
        customerId: 'u1',
        customerName: 'Kavindu Perera',
        customerEmail: 'customer@demo.com',
        customerPhone: '+94 77 123 4567',
        serviceId: 'svc1',
        serviceName: 'Classic Hair Cut',
        servicePrice: 1500,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-02-24',
        timeSlot: '10:00',
        duration: 30,
        status: 'Confirmed',
        paymentStatus: 'Unpaid',
        paymentMethod: 'Cash',
        createdAt: '2026-02-20T09:00:00Z',
    },
    {
        id: 'apt2',
        customerId: 'u1',
        customerName: 'Kavindu Perera',
        customerEmail: 'customer@demo.com',
        customerPhone: '+94 77 123 4567',
        serviceId: 'svc3',
        serviceName: 'Hydrating Facial',
        servicePrice: 3500,
        staffId: 's2',
        staffName: 'Rashmi Fernando',
        date: '2026-02-23',
        timeSlot: '14:00',
        duration: 60,
        status: 'Completed',
        paymentStatus: 'Paid',
        paymentMethod: 'Cash',
        createdAt: '2026-02-15T10:30:00Z',
    },
    {
        id: 'apt3',
        customerId: 'u2',
        customerName: 'Sithara De Silva',
        customerEmail: 'sithara@mail.com',
        customerPhone: '+94 77 987 6543',
        serviceId: 'svc5',
        serviceName: 'Bridal Makeup',
        servicePrice: 15000,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-02-25',
        timeSlot: '08:00',
        duration: 120,
        status: 'Pending',
        paymentStatus: 'Unpaid',
        paymentMethod: 'Cash',
        createdAt: '2026-02-22T14:00:00Z',
    },
    {
        id: 'apt4',
        customerId: 'u3',
        customerName: 'Malsha Rathnayake',
        customerEmail: 'malsha@mail.com',
        customerPhone: '+94 71 555 1234',
        serviceId: 'svc7',
        serviceName: 'Gel Nail Extension',
        servicePrice: 4000,
        staffId: 's2',
        staffName: 'Rashmi Fernando',
        date: '2026-02-23',
        timeSlot: '11:00',
        duration: 60,
        status: 'Confirmed',
        paymentStatus: 'Paid',
        paymentMethod: 'Cash',
        createdAt: '2026-02-20T11:00:00Z',
    },
    {
        id: 'apt5',
        customerId: 'u4',
        customerName: 'Dilini Madushika',
        customerEmail: 'dilini@mail.com',
        customerPhone: '+94 77 444 5555',
        serviceId: 'svc2',
        serviceName: 'Hair Color & Highlights',
        servicePrice: 5500,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-02-22',
        timeSlot: '15:00',
        duration: 90,
        status: 'Cancelled',
        paymentStatus: 'Refunded',
        createdAt: '2026-02-18T12:00:00Z',
    },
    {
        id: 'apt6',
        customerId: 'u2',
        customerName: 'Sithara De Silva',
        customerEmail: 'sithara@mail.com',
        customerPhone: '+94 77 987 6543',
        serviceId: 'svc10',
        serviceName: 'Ultimate Bridal Package',
        servicePrice: 45000,
        staffId: 's1',
        staffName: 'Nimasha Silva',
        date: '2026-03-05',
        timeSlot: '07:00',
        duration: 240,
        status: 'Pending',
        paymentStatus: 'Unpaid',
        paymentMethod: 'Cash',
        createdAt: '2026-02-28T16:00:00Z',
    }
];

// ==================== MOCK REVIEWS ====================
export const mockReviews: Review[] = [
    {
        id: 'r1',
        customerId: 'u1',
        customerName: 'Kavindu Perera',
        staffId: 's1',
        serviceId: 'svc1',
        rating: 5,
        comment: 'Nimasha is absolutely amazing! Perfect cut every time.',
        createdAt: '2026-02-10T10:00:00Z',
    },
    {
        id: 'r2',
        customerId: 'u2',
        customerName: 'Sithara De Silva',
        staffId: 's2',
        serviceId: 'svc3',
        rating: 4,
        comment: 'Great facial, my skin feels so refreshed. Will definitely come back!',
        createdAt: '2026-02-12T15:00:00Z',
    },
];

// ==================== MOCK PROMO CODES ====================
export const mockPromoCodes: PromoCode[] = [
    {
        id: 'p1',
        code: 'WELCOME20',
        discount: 20,
        isActive: true,
        expiresAt: '2026-12-31',
        usageLimit: 100,
        usedCount: 34,
    },
    {
        id: 'p2',
        code: 'BRIDAL15',
        discount: 15,
        isActive: true,
        expiresAt: '2026-06-30',
        usageLimit: 50,
        usedCount: 12,
    },
];

// ==================== REVENUE CHART DATA ====================
export const revenueData = [
    { month: 'Aug', revenue: 145000, appointments: 82 },
    { month: 'Sep', revenue: 162000, appointments: 95 },
    { month: 'Oct', revenue: 138000, appointments: 76 },
    { month: 'Nov', revenue: 195000, appointments: 110 },
    { month: 'Dec', revenue: 235000, appointments: 142 },
    { month: 'Jan', revenue: 178000, appointments: 98 },
    { month: 'Feb', revenue: 210000, appointments: 121 },
];

export const servicePopularity = [
    { name: 'Hair', value: 35 },
    { name: 'Facial', value: 25 },
    { name: 'Bridal', value: 15 },
    { name: 'Nails', value: 15 },
    { name: 'Massage', value: 10 },
];

export const peakHoursData = [
    { hour: '9AM', count: 12 },
    { hour: '10AM', count: 25 },
    { hour: '11AM', count: 30 },
    { hour: '12PM', count: 18 },
    { hour: '1PM', count: 10 },
    { hour: '2PM', count: 22 },
    { hour: '3PM', count: 28 },
    { hour: '4PM', count: 35 },
    { hour: '5PM', count: 20 },
    { hour: '6PM', count: 8 },
];

export const mockLeaveRequests: LeaveRequest[] = [
    {
        id: 'lv1',
        staffId: 's3',
        staffName: 'Tharushi Jayawardena',
        startDate: '2026-02-25',
        endDate: '2026-03-01',
        reason: 'Personal family emergency',
        status: 'Approved',
        appliedAt: '2026-02-20T10:00:00Z',
        approvedAt: '2026-02-21T09:00:00Z'
    },
    {
        id: 'lv2',
        staffId: 's1',
        staffName: 'Nimasha Silva',
        startDate: '2026-03-10',
        endDate: '2026-03-12',
        reason: 'Friend\'s wedding',
        status: 'Pending',
        appliedAt: '2026-02-22T14:30:00Z'
    }
];

export const mockGallery = [
    // --- HAIR CATEGORY (Freepik) ---
    {
        id: 'g2',
        title: 'Modern Afro-American Model',
        category: 'Hair',
        image: 'https://img.freepik.com/free-photo/afro-american-woman-model-studio_1303-13587.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g5',
        title: 'Professional Haircut in Progress',
        category: 'Hair',
        image: 'https://img.freepik.com/free-photo/beautiful-woman-has-cutting-hair-hairdresser_329181-1942.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g8',
        title: 'Blow Dry & Styling',
        category: 'Hair',
        image: 'https://img.freepik.com/free-photo/female-hairdresser-using-hairbrush-hair-dryer_329181-1929.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g14',
        title: 'Hair Wash Service',
        category: 'Hair',
        image: 'https://img.freepik.com/free-photo/customer-getting-wash-after-haircut_23-2148256876.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },

    // --- BRIDAL CATEGORY (Freepik) ---
    {
        id: 'g1',
        title: 'Bridal Makeup Portrait',
        category: 'Bridal',
        image: 'https://img.freepik.com/free-photo/female-model-wedding-bridal-makeup_114579-9312.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g11',
        title: 'Bride with Royal Jewelry',
        category: 'Bridal',
        image: 'https://img.freepik.com/free-photo/female-model-wedding-bridal-makeup-demonstrating-jewelry_114579-9311.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g7',
        title: 'Stylish Bride in Gown',
        category: 'Bridal',
        image: 'https://img.freepik.com/free-photo/young-beautiful-stylish-woman-wedding-dress_285396-7880.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g16',
        title: 'Happy Bride Portrait',
        category: 'Bridal',
        image: 'https://img.freepik.com/free-photo/portrait-beautiful-happy-bride-with-wedding-makeup-wedding-hairstyle_8353-5815.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },

    // --- NAILS CATEGORY (Freepik) ---
    {
        id: 'g4',
        title: 'Elegant Manicure',
        category: 'Nails',
        image: 'https://img.freepik.com/free-photo/hands-with-beautiful-nails_23-2149936852.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g13',
        title: 'Creative Nail Art Collage',
        category: 'Nails',
        image: 'https://img.freepik.com/free-photo/women-with-colorful-creative-nail-art-collage_23-2149936866.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g15_nails',
        title: 'Vibrant Creative Nails',
        category: 'Nails',
        image: 'https://img.freepik.com/free-photo/women-with-colorful-creative-nail-art_23-2149936865.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g17_nails',
        title: 'Professional Nail Application',
        category: 'Nails',
        image: 'https://img.freepik.com/free-photo/close-up-beautician-painting-woman-s-nails-with-brush-nail-salon_1139-1703.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },

    // --- MAKEUP CATEGORY (Freepik) ---
    {
        id: 'g6',
        title: 'Professional Makeup Application',
        category: 'Makeup',
        image: 'https://img.freepik.com/free-photo/professional-makeup-artist-working-with-young-woman_23-2148113098.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g19_makeup',
        title: 'Artist with Color Palette',
        category: 'Makeup',
        image: 'https://img.freepik.com/free-photo/crop-makeup-artist-with-palette-working-with-model_23-2147783935.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g20_makeup',
        title: 'Studio Makeup Session',
        category: 'Makeup',
        image: 'https://img.freepik.com/free-photo/makeup-artist-working-with-model-studio_23-2148113103.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g21_makeup',
        title: 'Detailed Makeup Technique',
        category: 'Makeup',
        image: 'https://img.freepik.com/free-photo/professional-makeup-artist-working_23-2148398598.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },

    // --- FACIAL CATEGORY (Freepik) ---
    {
        id: 'g3',
        title: 'Beauty Mask Application',
        category: 'Facial',
        image: 'https://img.freepik.com/free-photo/beautiful-woman-getting-beauty-treatment_329181-18790.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g22_facial',
        title: 'Professional Salon Facial',
        category: 'Facial',
        image: 'https://img.freepik.com/free-photo/cosmetologist-applying-mask-face-client-beauty-salon_1303-16770.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g23_facial',
        title: 'Relaxing Facial Treatment',
        category: 'Facial',
        image: 'https://img.freepik.com/free-photo/woman-relaxing-spa_329181-13154.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g24_facial',
        title: 'Premium Spa Experience',
        category: 'Facial',
        image: 'https://img.freepik.com/free-photo/young-woman-mask-face-relaxing-spa-salon_176420-7579.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },

    // --- MASSAGE CATEGORY (Freepik) ---
    {
        id: 'g9',
        title: 'Tranquil Spa Massage',
        category: 'Massage',
        image: 'https://img.freepik.com/free-photo/relaxing-spa-concept-with-woman_23-2147816920.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g10',
        title: 'Therapeutic Massage Session',
        category: 'Massage',
        image: 'https://img.freepik.com/free-photo/spa-massage-concept-with-woman_23-2147817035.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g25_massage',
        title: 'Professional Spa Treatment',
        category: 'Massage',
        image: 'https://img.freepik.com/free-photo/front-view-woman-working-spa_23-2150911820.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    },
    {
        id: 'g26_massage',
        title: 'Deep Tissue Therapy',
        category: 'Massage',
        image: 'https://img.freepik.com/free-photo/front-view-woman-working-spa_23-2150911815.jpg?uid=R214336655&ga=GA1.1.798508197.1772377356&semt=ais_hybrid&w=740&q=80',
    }
];
